# Сенсор доступности интернет соединения
- platform: template
  sensors:
    internet_is_available:
      value_template: "{{ states('binary_sensor.google_is_available') == 'on' or states('binary_sensor.yandex_is_available') == 'on' }}"
      device_class: connectivity