# -----------------------------------------------------------
# Автоматизации управления Охраной
# -----------------------------------------------------------

- alias: '001_Trigger_alarm_while_armed_away'
  description: "Тревога при открытии дверей в режиме 'Не дома'"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_contact_sensor_hallway_contact
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm
    
- alias: '001_Send_notification_when_alarm_triggered'
  description: "Все уведомления о состоянии сигнализации в Telegram"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
  condition:
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
  action:
    - choose:
        - conditions: "{{ trigger.to_state.state == 'triggered' }}"
          sequence:
            - service: telegram_bot.send_message
              data:
                title: "🔒 *Сигнализация*"
                message: "🚨 Сработала тревога!"
        - conditions: "{{ trigger.to_state.state == 'disarmed' }}"
          sequence:
            - service: telegram_bot.send_message
              data:
                title: "🔒 *Сигнализация*"
                message: "✅ Сигнализация снята с охраны!"
        - conditions: "{{ trigger.to_state.state == 'arming' }}"
          sequence:
            - service: telegram_bot.send_message
              data:
                title: "🔒 *Сигнализация*"
                message: "⏳ Сигнализация в режиме ожидания"
        - conditions: "{{ trigger.to_state.state == 'armed_away' }}"
          sequence:
            - service: telegram_bot.send_message
              data:
                title: "🔒 *Сигнализация*"
                message: "🔐 Сигнализация включена в режиме «Не дома»"
        - conditions: "{{ trigger.to_state.state == 'armed_home' }}"
          sequence:
            - service: telegram_bot.send_message
              data:
                title: "🔒 *Сигнализация*"
                message: "🏠 Сигнализация активирована в домашнем режиме!"
  mode: queued

- alias: '001_Trigger_alarm_while_armed_home'
  description: "Тревога в режиме дома"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_contact_sensor_hallway_contact
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_home
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm
    
- alias: "001_Security:_door_has_been_open_for_more_than_5_minutes"
  description: "Уведомление, если входная дверь открыта более 5 минут"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_contact_sensor_hallway_contact
      from: "off"
      to: "on"
      for: "00:05:00"
  condition:
    - condition: state
      entity_id: input_boolean.control_mode
      state: "on"
  action:
    - repeat:
        while:
          - condition: state
            entity_id: binary_sensor.door_window_contact_sensor_hallway_contact
            state: "on"
          - condition: state
            entity_id: input_boolean.control_mode
            state: "on"
        sequence:
          - service: telegram_bot.send_message
            data:
              title: "🔒 *Сигнализация*"
              message: "🚪 Входная дверь открыта больше 5 минут!"
          - delay: "00:05:00"
  mode: single
          
- alias: "001_Security:_Signaling._Forgot_to_put_it?"
  description: "Постановка на охрану если ни кого нет дома"
  trigger:
    - platform: time_pattern
      minutes: /5
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'disarmed'
    - condition: state
      entity_id: group.persons
      state: not_home
      for:
        minutes: 15
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
  action:
    - service: telegram_bot.send_message
      data:
        title: '🔒 *Сигнализация*'
        message: "🏠 Дом опустел. Ставлю на охрану."
        inline_keyboard:
          - '↩ Отменить?:/disarm'
    - delay: 00:00:05
    - service: script.turn_on
      entity_id: script.home_away_report
    - delay: 00:00:05
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm

- alias: "001_Security:_Signaling._Cancellation"
  description: "Отмена постановки на охрану через Telegram"
  trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
        command: "/disarm"
  condition:
    - condition: state
      entity_id: input_boolean.control_mode
      state: "on"
  action:
    - service: alarm_control_panel.alarm_disarm
      target:
        entity_id: alarm_control_panel.home_alarm
    - service: telegram_bot.send_message
      data:
        title: "🔒 *Сигнализация*"
        message: "✅ Постановка на охрану отменена"
  mode: single

- alias: "001_Security:_Signaling._Armed"
  description: "Постановка на охрану через Telegram"
  trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
        data: "/armed"
  condition:
    - condition: state
      entity_id: input_boolean.control_mode
      state: "on"
  action:
    - service: alarm_control_panel.alarm_arm_away
      target:
        entity_id: alarm_control_panel.home_alarm
    - service: telegram_bot.send_message
      data:
        title: "🔒 *Сигнализация*"
        message: "✅ Сигнализация поставлена на охрану"
  mode: single

- alias: "001_Security:_Signaling._disarming"
  description: "Снятие с охраны при нахождении персон в домашней зоне и статусе охраны не дома"
  trigger:
  - platform: geo_location
    source: group.persons
    zone: zone.home
    event: enter
  condition:
    - condition: state
      entity_id: 'alarm_control_panel.home_alarm'
      state: 'armed_away'
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
  action:
      - service: alarm_control_panel.alarm_disarm
        target:
          entity_id: alarm_control_panel.home_alarm

- alias: "001_Security:_Signaling._disarming_door_open"
  description: "Снятие с охраны при открытии двери и нахождении персон в домашней зоне"
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.door_window_contact_sensor_hallway_contact
    to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
    - condition: state
      entity_id: group.persons
      state: home
  action:
      - service: alarm_control_panel.alarm_disarm
        target:
          entity_id: alarm_control_panel.home_alarm

