# -----------------------------------------------------------
# Системные статусы и автоматизации
# -----------------------------------------------------------

- alias: "004_System_CPU_Temperature_alarm"
  description: "Тревога превышение температуры ЦПУ"
  trigger:
    platform: numeric_state
    entity_id: sensor.processor_temperature
    above: 60
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
      message: >
        ⚠  Превышение температуры процессора {{ states('sensor.processor_temperature') }}
        
- alias: "004_System_CPU_usage_alarm"
  description: "Тревога превышение порога утилизации процессора"
  trigger:
    platform: numeric_state
    entity_id: sensor.processor_use
    above: 90
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
      message: >
        ⚠  Тревога, высокая утилизация процессорного времени {{ states('sensor.processor_use') }}
    
- alias: "004_System_Disk_usage_alarm"
  description: "Тревога превышение порога использования диска"
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_use_percent
    above: 60
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
      message: >
        ⚠  Превышение используемого объёма диска {{ states('sensor.disk_use_percent') }}
    
- alias: "004_System_Memory_usage_alarm"
  description: "Тревога превышение порога использования памяти"
  trigger:
    platform: numeric_state
    entity_id: sensor.memory_use_percent
    above: 70
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
      message: >
        ⚠  Превышение используемого объёма памяти {{ states('sensor.date_time') }}
    
- alias: "004_Purge_Database"
  description: "Очистка базы данных"
  initial_state: True
  trigger:
      platform: time
      at: '02:22:22'
  action:
      service: recorder.purge
      data:
        keep_days: 3
        repack: true

- alias: "004_Zigbee_Bridge_state_change"
  description: "Уведомление о изменении состояния связи с Zigbee координатором"
  trigger:
  - platform: state
    entity_id: binary_sensor.zigbee2mqtt_bridge_connection_state
    from: online
    to: offline
  - platform: state
    entity_id: binary_sensor.zigbee2mqtt_bridge_connection_state
    from: offline
    to: online
  - platform: state
    entity_id: binary_sensor.zigbee2mqtt_bridge_connection_state_2
    from: online
    to: offline
  - platform: state
    entity_id: binary_sensor.zigbee2mqtt_bridge_connection_state_2
    from: offline
    to: online
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - service: telegram_bot.send_message
    data_template:
      title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
      message: >
        {% if trigger.to_state.state == 'offline' %}
          ⚠ Потеряна связь с Zigbee координатором {{ states('sensor.date_time') }}
        {% elif trigger.to_state.state == 'online' %}
          ⚠ Связь с Zigbee координатором восстановлена {{ states('sensor.date_time') }}
        {% endif %}


# - alias: "004_Zigbee_Bridge_state_offline"
#   description: "Уведомление о потере связи с координатором"
#   trigger:
#   - entity_id: binary_sensor.zigbee2mqtt_bridge_connection_state
#     from: online
#     platform: state
#     to: offline
#   - entity_id: binary_sensor.zigbee2mqtt_bridge_connection_state_2
#     from: online
#     platform: state
#     to: offline    
#   condition:
#   - condition: state
#     entity_id: input_boolean.control_mode
#     state: 'on'
#   action:
#   - data: {}
#     service: telegram_bot.send_message
#     data_template:
#       title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
#       message: >
#         ⚠  Потеряна связь с Zigbee координатором {{ states('sensor.date_time') }}
        
# - alias: "004_Zigbee_Bridge_state_online"
#   description: 'Отпрвка уведомления о восстановлении связи с координатором.'
#   trigger:
#   - entity_id: binary_sensor.zigbee2mqtt_bridge_connection_state
#     from: offline
#     platform: state
#     to: online
#   - entity_id: binary_sensor.zigbee2mqtt_bridge_connection_state_2
#     from: offline
#     platform: state
#     to: online
#   condition:
#   - condition: state
#     entity_id: input_boolean.control_mode
#     state: 'on'
#   action:
#   - data: {}
#     service: telegram_bot.send_message
#     data_template:
#       title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
#       message: >
#         ⚠  Cвязь с Zigbee координатором  восстановлена {{ states('sensor.date_time') }}

- alias: "004_Zigbee_unhealthy_alert"
  description: 'Оповещение о неисправности z2m'
  trigger:
  - platform: state
    entity_id: binary_sensor.z2m_health
    to: 'on'
  - platform: time
    at: '08:00:00'
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      message: |-
        ❌ Zigbee last seen ❌️:  
        {{"*"}}{{state_attr('binary_sensor.z2m_health', 'data')}}{{"*: "}}
        
- alias: "004_Zigbee_Device_Missing_Alert"
  description: "Оповещение о недоступных устройствах"
  trigger:
      - platform: time
        at: '07:00'
      - platform: time
        at: '16:00'
  condition:
      - condition: template
        value_template: |
          {% set ns = namespace(break = false) %} {% for state in states -%}
            {%- if state.attributes.last_seen %}
              {%- if (as_timestamp(now()) - as_timestamp(state.attributes.last_seen) > (60 * 60 * 20) ) and ns.break == false %}
                {%- set ns.break = true %}
                true
              {%- endif -%}
            {%- endif -%}
          {%- endfor %} 
  action:
      - service: telegram_bot.send_message
        data:
          message: >
            Some Zigbee devices haven't been seen lately... {% for state in states
            -%}
              {%- if (state.attributes.last_seen and not (state.name | regex_search('available|linkquality|power_on_behavior|state'))) %}
                {%- if (as_timestamp(now()) - as_timestamp(state.attributes.last_seen) > (60 * 60 * 20) ) %}
                  {{ ((as_timestamp(now()) - as_timestamp(state.attributes.last_seen)) / (3600)) | round(1) }} hours ago for {{"*"}}{{ state.name }}{{"*"}}
                  
                {%- endif -%}
              {%- endif -%}
            {%- endfor %}
  mode: single

- alias: "004_internet_ping_lost"
  description: "Оповещение о проблемах с интернетом"
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.internet_is_available
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: "*Problem with Internet!* ⚠️"
      message: >
        ⚠  Потеряна связь с интернетом {{ states('sensor.date_time') }}
        
- alias: "004_internet_ping_available"
  description: "Оповещение о восстновлении интренет соединения"
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.internet_is_available
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: "*Problem with Internet!* ⚠️"
      message: >
        👍  Cвязь с интернетом восстановлена {{ states('sensor.date_time') }}

- alias: "The camera on the 7th floor is unavailable"
  description: ''
  trigger:
  - type: not_connected
    platform: device
    device_id: 20e98bc5be4b8613732f00a06a0e4db7
    entity_id: 40cd5912aca5be9712a3a8150cafdc21
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: "*Problem with Cam* ⚠️"
      message: >
        ⚠  Потеряна связь с камерой на 7 этаже {{ states('sensor.date_time') }}

- alias: "The camera on the 7th floor is available"
  description: ''
  trigger:
  - type: connected
    platform: device
    device_id: 20e98bc5be4b8613732f00a06a0e4db7
    entity_id: 40cd5912aca5be9712a3a8150cafdc21
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: "*Problem with Cam* ⚠️"
      message: >
        👍  Связь с камерой на 7 этаже восстановлена {{ states('sensor.date_time') }}

- alias: "004_Torrent_Completed"
  trigger:
  - type: value
    platform: device
    device_id: 9fe90303300721798204a27de18b6855
    entity_id: ac81c608d6277c377994b65f16852fcd
    domain: sensor
    below: 0
  condition:
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
  action:
    service: telegram_bot.send_message
    data_template:
      message: "Загрузка torrent-файла завершена"

- alias: "004_Полнолуние"
  trigger:
    platform: state
    entity_id: sensor.moon_phase
    to: "full_moon"
  condition:
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
  action:
    service: telegram_bot.send_message
    data_template:
      message: "Сегодня полнолуние!"
      
- alias: "004_HACS:_New_Component_Version_Available"
  trigger:
    platform: state
    entity_id: sensor.hacs
  condition:
    - condition: template
      value_template: "{{ (states('sensor.hacs') | int) > 0 }}"
  action:
    service: telegram_bot.send_message
    data_template:
      message: |
        _INFO:_ Доступны новые версии Custom Components (HACS) ({{ states('sensor.hacs') }}):
        {%- for repo in state_attr('sensor.hacs', 'repositories') %}
        {{ repo.display_name }} (_{{ repo.installed_version }}_ -> _{{ repo.available_version }}_){% if not loop.last %}, {% endif %}
        {%- endfor -%}

- alias: "004_HASSIO:_New_Home_Assistant_Version_Available"
  description: ''
  trigger:
  - type: update
    platform: device
    device_id: 19d4d960bd60e915e329874140bcf74e
    entity_id: 58a102ffa5bc377876118d59b4698200
    domain: binary_sensor
  condition: 
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
  action:
    - service: telegram_bot.send_message
      data_template:
        message: "_INFO:_ Доступна новая версия Home Assistant ({{ state_attr('binary_sensor.home_assistant_versions_update_available') }})"





        




