# -----------------------------------------------------------
# Системные статусы и автоматизации
# -----------------------------------------------------------

- alias: "004_System_CPU_Temperature_alarm"
  description: "Тревога превышение температуры ЦПУ"
  trigger:
  - entity_id: sensor.processor_temperature
    for: 00:01:00
    platform: state
    above: '30'
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
      message: >
        ⚠  Превышение температуры процессора {{ states('sensor.date_time') }}
        
- alias: "004_System_CPU_usage_alarm"
  description: "Тревога превышение порога утилизации процессора"
  trigger:
  - type: value
    platform: device
    device_id: 80571189ddbc66c3270d82cd2b748f5c
    entity_id: d95e05f2df4dcc7cd7d4ff4772775232
    domain: sensor
    above: 50
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
      message: >
        ⚠  Тревого высокая утилизация процессорного времени{{ states('sensor.date_time') }}
    
- alias: "004_System_Disk_usage_alarm"
  description: "Тревога превышение порога использования диска"
  trigger:
  - type: value
    platform: device
    device_id: 80571189ddbc66c3270d82cd2b748f5c
    entity_id: 117fc68ac6baaaca9bb044f6b32b0e19
    domain: sensor
    above: 50
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
      message: >
        ⚠  Превышение используемого объёма диска {{ states('sensor.date_time') }}
    
- alias: "004_System_Memory_usage_alarm"
  description: "Тревога превышение порога использования памяти"
  trigger:
  - type: value
    platform: device
    device_id: 80571189ddbc66c3270d82cd2b748f5c
    entity_id: b78c3bf0c2537b65653f1f98cb855330
    domain: sensor
    above: 50
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
      message: >
        ⚠  Превышение используемого объёма памяти {{ states('sensor.date_time') }}
    
- alias: "004_Purge_Database"
  description: "Очистка базы данных"
  initial_state: True
  trigger:
      platform: time
      at: '02:22:22'
  action:
      service: recorder.purge
      data:
        keep_days: 3
        repack: true

- alias: "004_Zigbee_Bridge_state_offline"
  description: "Уведомление о потере связи с координатором"
  trigger:
  - entity_id: sensor.bridge_state
    from: online
    platform: state
    to: offline
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
      message: >
        ⚠  Потеряна связь с Zigbee координатором {{ states('sensor.date_time') }}
        
- alias: "004_Zigbee_Bridge_state_online"
  description: 'Отпрвка уведомления о восстановлении связи с координатором.'
  trigger:
  - entity_id: sensor.bridge_state
    from: offline
    platform: state
    to: online
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
      message: >
        ⚠  Cвязь с Zigbee координатором  восстановлена {{ states('sensor.date_time') }}

- alias: "004_Zigbee_unhealthy_alert"
  description: 'Оповещение о неисправности z2m'
  trigger:
  - platform: state
    entity_id: binary_sensor.z2m_health
    to: 'on'
  - platform: time
    at: '08:00:00'
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      message: |-
        ❌ Zigbee last seen ❌️:  
        {{"*"}}{{state_attr('binary_sensor.z2m_health', 'data')}}{{"*: "}}
        
- alias: "004_Zigbee_Device_Missing_Alert"
  description: "Оповещение о недоступных устройствах"
  trigger:
      - platform: time
        at: '07:00'
      - platform: time
        at: '16:00'
  condition:
      - condition: template
        value_template: |
          {% set ns = namespace(break = false) %} {% for state in states -%}
            {%- if state.attributes.last_seen %}
              {%- if (as_timestamp(now()) - as_timestamp(state.attributes.last_seen) > (60 * 60 * 20) ) and ns.break == false %}
                {%- set ns.break = true %}
                true
              {%- endif -%}
            {%- endif -%}
          {%- endfor %} 
  action:
      - service: telegram_bot.send_message
        data:
          message: >
            Some Zigbee devices haven't been seen lately... {% for state in states
            -%}
              {%- if (state.attributes.last_seen and not (state.name | regex_search('available|linkquality|power_on_behavior|state'))) %}
                {%- if (as_timestamp(now()) - as_timestamp(state.attributes.last_seen) > (60 * 60 * 20) ) %}
                  {{ ((as_timestamp(now()) - as_timestamp(state.attributes.last_seen)) / (3600)) | round(1) }} hours ago for {{"*"}}{{ state.name }}{{"*"}}
                  
                {%- endif -%}
              {%- endif -%}
            {%- endfor %}
  mode: single

- alias: "004_internet_ping_lost"
  description: "Оповещение о проблемах с интернетом"
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.internet_is_available
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: "*Problem with Internet!* ⚠️"
      message: >
        ⚠  Потеряна связь с интернетом {{ states('sensor.date_time') }}
        
- alias: "004_internet_ping_available"
  description: "Оповещение о восстновлении интренет соединения"
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.internet_is_available
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - data: {}
    service: telegram_bot.send_message
    data_template:
      title: "*Problem with Internet!* ⚠️"
      message: >
        👍  Cвязь с интернетом восстановлена {{ states('sensor.date_time') }}