# -----------------------------------------------------------
# Автоматизации управления датчиками протечки
# -----------------------------------------------------------

- alias: "006_temporarily_disable_notification"
  description: "Временно отключить оповещение о протечке"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      command: '/disable_notification_leak'
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.water_mode_alarm
  - service: telegram_bot.send_message
    data:
      title: "🎉 *Сообщение системы*" 
      message: |
           ⚠  Отключение режима отслеживания датчиков протечки на 1 час.
  - delay: 01:00:00
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.water_mode_alarm
  - service: telegram_bot.send_message
    data:
      title: "🎉 *Сообщение системы*" 
      message: |
           ⚠  Режим отслеживания датчиков протечки включен.

- alias: "006_Alarm_Aqara_water_sensor_bathroom_ON"
  description: "Оповещение о протечке в ванной"
  trigger:
    platform: state
    entity_id: binary_sensor.water_leak_sensor_bathroom_water_leak
    to: "on"
  condition: []
  action:
    - repeat:
        while:
          - condition: state
            entity_id: binary_sensor.water_leak_sensor_bathroom_water_leak
            state: 'on'
          - condition: state
            entity_id: input_boolean.water_mode_alarm
            state: 'on'
        sequence:
          - service: telegram_bot.send_message
            data:
              title: "🎉 *Сообщение системы*" 
              message: "⚠  Протечка в ванной"
              inline_keyboard: 
                - 'Временно отключить?:/disable_notification_leak'
          - service: script.turn_on
            entity_id: 
                - script.yandex_tts3
          - service: media_player.play_media
            data_template:
                entity_id: media_player.mpd
                media_content_id: "http://10.123.10.84:8123/local/sound/alarm_2.mp3"
                media_content_type: 'music'
          - delay: 00:01:00

- alias: "006_Alarm_Aqara_water_sensor_bathroom_OFF"
  description: 'Оповещение о устранении протечки в ванной'
  trigger:
    entity_id: binary_sensor.water_leak_sensor_bathroom_water_leak
    platform: state
    to: 'off'
  condition: []
  action:
    - service: telegram_bot.send_message
      data_template:
        title: "🎉 *Сообщение системы*" 
        message: | 
             ⚠  Протечка в ванной устранена!
    - service: script.turn_on
      entity_id: 
         - script.yandex_tts5

- alias: "006_Alarm_Aqara_water_sensor_kitchen_ON"
  description: "Оповещение о протечке на кухне"
  trigger:
    entity_id: binary_sensor.water_leak_sensor_kitchen_water_leak
    platform: state
    to: 'on'
  condition: []
  action:
    - repeat:
        while:
          - condition: state
            entity_id: binary_sensor.water_leak_sensor_kitchen_water_leak
            state: 'on'
          - condition: state
            entity_id: input_boolean.water_mode_alarm
            state: 'on'
        sequence:
          - service: telegram_bot.send_message
            data:
              title: "🎉 *Сообщение системы*" 
              message: "⚠  Протечка на кухне"
              inline_keyboard: 
                - 'Временно отключить?:/disable_notification_leak'
          - service: script.turn_on
            entity_id: 
                - script.yandex_tts4
          - service: media_player.play_media
            data_template:
                entity_id: media_player.mpd
                media_content_id: "http://10.123.10.84:8123/local/sound/alarm_2.mp3"
                media_content_type: 'music'
          - delay: 00:01:00
             
- alias: "006_Alarm_Aqara_water_sensor_kitchen_OFF"
  description: 'Оповещение о устранении протечки на кухне'
  trigger:
    entity_id: binary_sensor.water_leak_sensor_kitchen_water_leak
    platform: state
    to: 'off'
  condition: []
  action:
    - service: telegram_bot.send_message
      data_template:
        title: "🎉 *Сообщение системы*" 
        message: | 
             ⚠  Протечка на кухне устранена 
    - service: script.turn_on
      entity_id: 
         - script.yandex_tts5
    
