# -----------------------------------------------------------
# Автоматизации управления освещениеме в прихожей
# -----------------------------------------------------------

- alias: "007_Hallway_turn_on_light"
  description: 'Включении освещения при открытии входной двери и отсутвии движения 10 минут'
  trigger:
  - type: opened
    platform: device
    device_id: 7d430a026d2f4adfa816429e11b8c63c
    entity_id: a10f7d31ded43ca1d3510de02907d35a
    domain: binary_sensor
  condition:
    - condition: state
      entity_id: input_boolean.auto_light_on_off_hallway
      state: 'on'
    - condition: and
      conditions:
          - condition: state
            entity_id: binary_sensor.kam02_home_cell_motion_detection
            state: 'on'
            for:
              hours: 0
              minutes: 10
              seconds: 0
          - condition: state
            entity_id: light.0x54ef4410008178c4_right
            state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.0x54ef4410008178c4_right

- alias: "007_Hallway_turn_off_light_5_min_(no_motion)"
  description: 'Отключение освещения при отсутвии движения 10 минут'
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.kam02_home_cell_motion_detection
    to: 'off'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.auto_light_on_off_hallway
    state: 'on'
  - condition: and
    conditions:
    - condition: state
      entity_id: light.0x54ef4410008178c4_right
      state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.0x54ef4410008178c4_right
      
- alias: "007_motion_hallway_time"
  description: 'Запись последнего движения в коридоре'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.kam02_home_cell_motion_detection
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d00010f8920"
      payload: "{{ states('sensor.date_time')}}"
      retain: true
      
- alias: "007_motion_hallway_time"
  description: 'Запись последнего открытия входной двери'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.door_window_contact_sensor_hallway_contact
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/prxine9ptea758sx"
      payload: "{{ states('sensor.date_time')}}"
      retain: true
      
