- alias: "010_Let's_Encrypt_Renewal"
  trigger:
  - platform: time
    at: '00:00:00'
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
  - delay: 00:02:00
  - service: hassio.addon_restart
    data:
      addon: core_nginx_proxy
