# -----------------------------------------------------------
# Автоматизации управления датчиком дыма
# -----------------------------------------------------------

- alias: "013_Smoke_Detector_Alarm_ON"
  description: "Оповещение о обнаружении дыма"
  trigger:
    entity_id: binary_sensor.honeywell_detector_smoke
    platform: state
    to: 'on'
  condition: []
  action:
    - repeat:
        while:
          - condition: state
            entity_id: binary_sensor.honeywell_detector_smoke
            state: 'on'
        sequence:
          - service: telegram_bot.send_message
            data:
              title: "🎉 *Сообщение системы*" 
              message: |
                   ⚠  Внимание! Датчик обнаружил дым! 
          - service: script.turn_on
            entity_id: 
                - script.yandex_tts8
          - delay: 00:00:05
          - service: telegram_bot.delete_message
            data:
              chat_id: !secret telegram_bot_allowed_chat_id1
              message_id: last
          - delay: 00:00:05

- alias: "013_Smoke_Detector_Alarm_OFF"
  description: "Оповещение о устранении дыма"
  trigger:
    entity_id: binary_sensor.honeywell_detector_smoke
    platform: state
    to: 'off'
  condition: []
  action:
  - service: telegram_bot.send_message
    data_template:
        title: "🎉 *Сообщение системы*" 
        message: | 
             ⚠  Внимание! Источник дыма устранен!
  - delay: 00:00:05
  - service: telegram_bot.delete_message
    data:
      chat_id: !secret telegram_bot_allowed_chat_id1
      message_id: last
     
