# -----------------------------------------------------------
# Автоматизации управления роботом пылесосом
# -----------------------------------------------------------

- alias: "023_Vacuum_started_cleaning"
  trigger:
    platform: state
    entity_id: vacuum.dreame_mc1808_e6fb_robot_cleaner
    to: cleaning
  action:
  - service: telegram_bot.send_message
    data:
      title: "🎉 *Сообщение системы*" 
      message: | 
        "🤖 Робот начал уборку!" 
        
- alias: "023_Vacuum_stopped_cleaning"
  trigger:
    platform: state
    entity_id: vacuum.dreame_mc1808_e6fb_robot_cleaner
    from: returning
    to: docked
  action:
    - service: telegram_bot.send_message
      data:
        title: "🎉 *Сообщение системы*" 
        message: "Уборка успешно завершена после {{ state_attr('vacuum.mi_robot', 'cleaning_time') }} минут."
        
- alias: "023_Vacuum_reset_to_standard_mode"
  trigger:
    platform: state
    entity_id: vacuum.dreame_mc1808_e6fb_robot_cleaner
    to: docked
  action:
  - device_id: 0becfdd23f8e874142bdc8a3bf15df57
    domain: select
    entity_id: 62767688245e424b4b2164e28fd5b3f4
    type: select_option
    option: 标准
      
- alias: "023_Vacuum_reset_cleaned_today"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: vacuum.dreame_mc1808_e6fb_robot_cleaner
    to: docked
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.cleaned_today

- alias: "023_Vacuum_reminder_notification"
  trigger:
  - platform: state
    entity_id: input_boolean.cleaned_today
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.cleaned_today
      state: 'on'
  action:
    service: telegram_bot.send_message
    data:
      title: "🎉 *Сообщение системы*"
      message: "Пылесос сегодня в 13:00 выполнит уборку, пожалуйста убери вещи с пола и закрой дверь в ванную!"
      
- alias: "023_Vacuum_cleanup_if_nobody_is_home"
  trigger:
    - platform: time
      at: "13:00"
  condition:
    - condition: time
      after: "13:00:00"
      before: "22:00:00"
    - condition: state
      entity_id: input_boolean.cleaned_today
      state: "on"
    - condition: state
      entity_id: group.persons
      state: not_home
    - condition: state
      entity_id: binary_sensor.motion_in_home
      state: 'off'
      for:
       minutes: 30
  action:
  - device_id: 0becfdd23f8e874142bdc8a3bf15df57
    domain: vacuum
    entity_id: 7e1b21955d240e260cc6153548dc9d93
    type: clean
  - device_id: 0becfdd23f8e874142bdc8a3bf15df57
    domain: select
    entity_id: 62767688245e424b4b2164e28fd5b3f4
    type: select_option
    option: 中档
    
- alias: "023_Vacuum_cleanup:_ON_away"
  description: ''
  trigger:
    - platform: state
      entity_id: group.persons
      from: home
      to: not_home
  condition: 
    condition: time
    after: "06:00:00"
    before: "13:00:00"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.cleaned_today
  mode: single

  
    
    
    
    