# -----------------------------------------------------------
# Автоматизации управления домофоном
# -----------------------------------------------------------

- alias: "025_Intercom_ring"
  description: "Отправка уведомления в телеграмм"
  trigger:
    platform: state
    entity_id: sensor.0x00124b002262723d_state
    to: "ring"
  condition: 
    - condition: state
      entity_id: input_boolean.intercom_mode
      state: 'on'
  action:
    - service: telegram_bot.send_message
      data:
        title: "🎉 *Сообщение системы*"
        message: "Кто-то звонит в домофон!"
        inline_keyboard:
          - 'Открыть?:/door_open'
          - 'Не открывать!:/door_drop'

- alias: "025_doorbell_notify_intercom_open"
  description: "Открыть дверь при звонке"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      command: '/door_open'
  condition:
    - condition: state
      entity_id: input_boolean.intercom_mode
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.intercom_open_once
      
- alias: "025_doorbell_notify_intercom_drop"
  description: "Не открывать дверь при звонке"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      command: '/door_drop'
  condition:
    - condition: state
      entity_id: input_boolean.intercom_mode
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.intercom_open_drop
      
- alias: "025_intercom_notify_reset_mode"
  trigger:
  - platform: time
    at: '22:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.intercom_mode
        state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.intercom_open_never

- alias: "025_intercom_notify_Off"
  trigger:
  - platform: time
    at: '22:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.intercom_mode
        state: 'on'
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.0x00124b002262723d_sound

- alias: "025_intercom_notify_On"
  trigger:
  - platform: time
    at: '08:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.intercom_mode
        state: 'on'
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.0x00124b002262723d_sound