# -----------------------------------------------------------
# Автоматизации управления светом в гостинной
# -----------------------------------------------------------



- alias: "029_light_living_room_off"
  description: 'Выключение подсветки по времени с повторными попытками и уведомлением'
  trigger:
    - platform: time
      at: input_datetime.light_living_room_off
  condition:
    - condition: state
      entity_id: input_boolean.auto_light_on_off_girlianda_ws2811
      state: 'on'
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
    - condition: state
      entity_id: light.wled
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.wled
    - repeat:
        while:
            condition: or
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: light.wled
                    state: "off"
                  - condition: state
                    entity_id: light.wled
                    state: unavailable
                  - condition: state
                    entity_id: light.wled
                    state: unknown
        sequence:
            - service: light.turn_off
              entity_id: light.wled
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled
            - service: telegram_bot.send_message
              data:
                message: |
                    ⚠️ Лента в гостинной не выключилась в течение 10 минут.

- alias: "029_light_living_room_3%"
  description: 'Изменение яркости подсветки по времени в 22:00'
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.auto_light_on_off_girlianda_ws2811
    state: 'on'
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  - condition: and
    conditions:
      - condition: state
        entity_id:
            - light.wled
        match: any
        state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.wled
        brightness_pct: 3

- alias: "029_light_living_room_50%_on"
  description: 'Включение подсветки по времени с уведомлением о задержке и повторным включением'
  trigger:
    - platform: time
      at: input_datetime.light_living_room_on
  condition:
    - condition: state
      entity_id: input_boolean.auto_light_on_off_girlianda_ws2811
      state: 'on'
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
    - condition: and
      conditions:
        - condition: state
          entity_id:
            - light.wled
          match: any
          state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.wled
        brightness_pct: 50
    - repeat:
        while:
            condition: or
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: light.wled
                    state: "off"
                  - condition: state
                    entity_id: light.wled
                    state: unavailable
                  - condition: state
                    entity_id: light.wled
                    state: unknown
        sequence:
            - service: light.turn_on
              entity_id: light.wled
            - delay: 00:02:00
            - service: light.turn_on
              entity_id: light.wled
            - delay: 00:02:00
            - service: light.turn_on
              entity_id: light.wled
            - delay: 00:02:00
            - service: light.turn_on
              entity_id: light.wled
            - delay: 00:02:00
            - service: light.turn_on
              entity_id: light.wled
            - delay: 00:02:00
            - service: light.turn_on
              entity_id: light.wled
            - service: telegram_bot.send_message
              data:
                message: |
                    ⚠️ Лента в гостинной не включилась в течение 10 минут.

- alias: "029_light_living_room_turn_on_automatic"
  description: 'Применение пресета после сброса питания'
  trigger:
  - platform: state
    entity_id:
    - light.wled
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.auto_light_on_off_girlianda_ws2811
    state: 'on'
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - device_id: 74f618890967fe0de63bf749d22803b6
    domain: select
    entity_id: select.wled_preset
    type: select_option
    option: Preset 3
  mode: single
 
- alias: "029_light_living_room_Christmas_tree" 
  description: "Переключение пресетов на ёлке"
  mode: single
  triggers:
    - platform: time_pattern
      minutes: '/15'
  conditions:
    - condition: device
      type: is_on
      device_id: c8e395bfdad8c52e8cd70265ff22459f
      entity_id: c5d4876ae57a4d0376d8af628a9ced88
      domain: light
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
  actions:
    - device_id: c8e395bfdad8c52e8cd70265ff22459f
      domain: select
      entity_id: 40f94190fffce08de1ad8c65a3e6019b
      type: select_next
      cycle: true
      
- alias: "029_light_living_room_Christmas_tree_on_off_segment"
  description: "Синхронизация включения и отключения сегментов ёлки"
  triggers:
  - type: changed_states
    device_id: c8e395bfdad8c52e8cd70265ff22459f
    entity_id: c5d4876ae57a4d0376d8af628a9ced88
    domain: light
    trigger: device
  conditions:
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  actions:
  - choose:
    - conditions:
      - condition: device
        type: is_on
        device_id: c8e395bfdad8c52e8cd70265ff22459f
        entity_id: c5d4876ae57a4d0376d8af628a9ced88
        domain: light
      sequence:
      - type: turn_on
        device_id: c8e395bfdad8c52e8cd70265ff22459f
        entity_id: c93276eb1b6e97d703ea6ca5d8f05337
        domain: light
    - conditions:
      - condition: device
        type: is_off
        device_id: c8e395bfdad8c52e8cd70265ff22459f
        entity_id: c5d4876ae57a4d0376d8af628a9ced88
        domain: light
      sequence:
      - type: turn_off
        device_id: c8e395bfdad8c52e8cd70265ff22459f
        entity_id: c93276eb1b6e97d703ea6ca5d8f05337
        domain: light
  mode: single
  

