# -----------------------------------------------------------
# Автоматизации управления присутсвием
# -----------------------------------------------------------

- alias: "031_Home_away_OFF_devices"
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '/30'
    seconds: '0'
  condition:
      - condition: state
        entity_id: binary_sensor.motion_in_home
        state: 'off'
        for:
          minutes: 30
      - condition: state
        entity_id:
            - light.0x54ef4410008178c4_right
            - light.0x54ef4410008178c4_left
            - light.0xec1bbdfffe803961
            - light.0x00158d00028b38b0
            - light.wled
            - media_player.lg_webos_smart_tv
            - light.wled_strip_elka
            - light.0x00158d0003985898
            - media_player.yandex_station_540078920110102034cf
            - light.0x54ef4410008194ad
            - fan.rele01
            - light.0x00158d00044f539d
            - light.wled_2
            - media_player.yandex_station_m003nh2007vwab
            - light.wled_bedroom
        match: any
        state: "on"
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: "armed_away"
      - condition: state
        entity_id: input_boolean.control_mode
        state: "on"
  action:
    - service: telegram_bot.send_message
      data:
        message: "Похоже в доме остались включенные приборы."
        inline_keyboard:
          - '💡 Выключить всё:/turn_off'
