# -----------------------------------------------------------
# Автоматизации управления устройствами в детской
# -----------------------------------------------------------



- alias: "032_light_child_room_off"
  description: 'Выключение подсветки в детской по времени с повторными попытками и уведомлением'
  trigger:
    - platform: time
      at: input_datetime.light_child_room_off
  condition:
    - condition: state
      entity_id: input_boolean.auto_light_child_room
      state: 'on'
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
    - condition: state
      entity_id: light.wled_2
      state: "on"
  action:
    - repeat:
        while:
            condition: or
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: light.wled_2
                    state: "on"
                  - condition: state
                    entity_id: light.wled_2
                    state: unavailable
                  - condition: state
                    entity_id: light.wled_2
                    state: unknown
        sequence:
            - service: light.turn_off
              entity_id: light.wled_2
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled_2
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled_2
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled_2
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled_2
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled_2
            - service: telegram_bot.send_message
              data:
                message: |
                  ⚠️ Лента в детской не выключилась в течение 10 минут.
            - delay: 00:00:05

- alias: "032_light_child_room_3%_strip_on_22:00"
  description: 'Изменение яркости подсветки в 22:00'
  trigger:
    - platform: time_pattern
      minutes: "/10"
  condition: 
    - condition: state
      entity_id: input_boolean.auto_light_child_room
      state: 'on'
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
    - condition: time
      after: '22:00:00'
    - condition: state
      entity_id: light.wled_2
      state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.wled_2
        brightness_pct: 15
              
- alias: "032_light_child_room_50%_on"
  description: 'Включение подсветки по времени с уведомлением о задержке и повторным включением'
  trigger:
    - platform: time
      at: input_datetime.light_child_room_on
  condition:
    - condition: state
      entity_id: input_boolean.auto_light_child_room
      state: 'on'
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
    - condition: and
      conditions:
        - condition: state
          entity_id:
            - light.wled_2
          match: any
          state: "off"
  action:
    - repeat:
        while:
            condition: or
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: light.wled_2
                    state: "off"
                  - condition: state
                    entity_id: light.wled_2
                    state: unavailable
                  - condition: state
                    entity_id: light.wled_2
                    state: unknown
        sequence:
            - service: light.turn_on
              data:
                entity_id: light.wled_2
                brightness_pct: 50
            - delay: 00:02:00
            - service: light.turn_on
              data:
                entity_id: light.wled_2
                brightness_pct: 50
            - delay: 00:02:00
            - service: light.turn_on
              data:
                entity_id: light.wled_2
                brightness_pct: 50
            - delay: 00:02:00
            - service: light.turn_on
              data:
                entity_id: light.wled_2
                brightness_pct: 50
            - delay: 00:02:00
            - service: light.turn_on
              data:
                entity_id: light.wled_2
                brightness_pct: 50
            - delay: 00:02:00
            - service: light.turn_on
              data:
                entity_id: light.wled_2
                brightness_pct: 50
            - service: telegram_bot.send_message
              data:
                message: |
                  ⚠️ Лента в детской не включилась в течение 10 минут.
            - delay: 00:00:05

- alias: "032_light_child_room_turn_on_automatic_wled_2"
  description: 'Применение пресета после сброса питания'
  trigger:
  - platform: state
    entity_id:
    - light.wled_2
    from: 'off'
    to: 'on'
  condition: 
  - condition: state
    entity_id: input_boolean.auto_light_child_room
    state: 'on'
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - device_id: c4a1f53e2bf2693166df40cc440eb622
    domain: select
    entity_id: select.wled_girlyanda_preset
    type: select_option
    option: Preset 8
  mode: single