# -----------------------------------------------------------
# Автоматизации управления устройствами в детской
# -----------------------------------------------------------

# - alias: "032_light_child_room_off"
#   description: 'Выключение подсветки по времени'
#   trigger:
#   - platform: time
#     at: input_datetime.light_child_room_off
#   condition:
#   - condition: state
#     entity_id: input_boolean.auto_light_child_room
#     state: 'on'
#   - condition: state
#     entity_id: input_boolean.control_mode
#     state: 'on'
#   - condition: and
#     conditions:
#       - condition: state
#         entity_id:
#             - light.wled_2
#         match: any
#         state: "on"
#   action:
#     - service: light.turn_off
#       entity_id: light.wled_2

- alias: "032_light_child_room_off"
  description: 'Выключение подсветки в детской по времени с повторными попытками и уведомлением'
  trigger:
    - platform: time
      at: input_datetime.light_child_room_off
  condition:
    - condition: state
      entity_id: input_boolean.auto_light_child_room
      state: 'on'
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
    - condition: state
      entity_id: light.wled_2
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.wled_2
    - repeat:
        count: 10  # 10 попыток выключения (10 минут)
        sequence:
          - delay: "00:01:00"  # Задержка 1 минута перед повторной проверкой
          - condition: state
            entity_id: light.wled_2
            state: "on"  # Проверка, выключилась ли лента
          - service: light.turn_off
            entity_id: light.wled_2  # Повторное выключение
    - condition: state
      entity_id: light.wled_2
      state: "on"  # Если после всех попыток лента все еще включена
    - service: telegram_bot.send_message
      data:
        title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
        message: |
          ⚠️ Лента в детской не выключилась в течение 10 минут.

- alias: "032_light_child_room_3%_strip_on_22:00"
  description: 'Изменение яркости подсветки в 22:00'
  trigger:
    - platform: time_pattern
      minutes: "/10"
  condition: 
    - condition: state
      entity_id: input_boolean.auto_light_child_room
      state: 'on'
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
    - condition: time
      after: '22:00:00'
    - condition: state
      entity_id: light.wled_2
      state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.wled_2
        brightness_pct: 15
              
# - alias: "032_light_child_room_50%_on"
#   description: 'Включение подсветки по времени'
#   trigger:
#   - platform: time
#     at: input_datetime.light_child_room_on
#   condition:
#   - condition: state
#     entity_id: input_boolean.auto_light_child_room
#     state: 'on'
#   - condition: state
#     entity_id: input_boolean.control_mode
#     state: 'on'
#   - condition: and
#     conditions:
#       - condition: state
#         entity_id:
#             - light.wled_2
#         match: any
#         state: "off"
#   action:
#     - service: light.turn_on
#       data:
#         entity_id: light.wled_2
#         brightness_pct: 50

- alias: "032_light_child_room_50%_on"
  description: 'Включение подсветки по времени с уведомлением о задержке и повторным включением'
  trigger:
    - platform: time
      at: input_datetime.light_child_room_on
  condition:
    - condition: state
      entity_id: input_boolean.auto_light_child_room
      state: 'on'
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
    - condition: and
      conditions:
        - condition: state
          entity_id:
            - light.wled_2
          match: any
          state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.wled_2
        brightness_pct: 50
    - repeat:
        count: 3  # Повторить дважды, всего 4 попытки (первая + 3 повтора)
        sequence:
          - delay: "00:01:00"  # Задержка в 1 минут между попытками
          - condition: state
            entity_id: light.wled_2
            state: "off"  # Проверка, что свет не включился
          - service: light.turn_on
            data:
              entity_id: light.wled_2
              brightness_pct: 50  # Повторная попытка включить свет
    - condition: state
      entity_id: light.wled_2
      state: "off"  # Если после всех попыток свет все еще выключен
    - service: telegram_bot.send_message
      data:
        title: '*ОПОВЕЩЕНИЕ СИСТЕМЫ:*'
        message: |
          ⚠️ Лента в детской не включилась в течение 5 минут.
        
- alias: "032_light_child_room_turn_on_automatic_wled_2"
  description: 'Применение пресета после сброса питания'
  trigger:
  - platform: state
    entity_id:
    - light.wled_2
    from: 'off'
    to: 'on'
  condition: 
  - condition: state
    entity_id: input_boolean.auto_light_child_room
    state: 'on'
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - device_id: c4a1f53e2bf2693166df40cc440eb622
    domain: select
    entity_id: select.wled_girlyanda_preset
    type: select_option
    option: Preset 8
  mode: single