# -----------------------------------------------------------
# Автоматизации управления освещением в спальне
# -----------------------------------------------------------



- alias: "033_light_bedroom_off"
  description: 'Выключение подсветки в спальне по времени с повторными попытками и уведомлением'
  trigger:
    - platform: time
      at: input_datetime.light_bedroom_off
  condition:
    - condition: state
      entity_id: input_boolean.auto_light_bedroom_on_off
      state: 'on'
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
    - condition: state
      entity_id: light.wled_bedroom
      state: "on"
  action:
    - repeat:
        while:
          - condition: or
            conditions:
              - condition: state
                entity_id: light.wled_bedroom
                state: "on"
              - condition: state
                entity_id: light.wled_bedroom
                state: unavailable
              - condition: state
                entity_id: light.wled_bedroom
                state: unknown
        sequence:
            - service: light.turn_off
              entity_id: light.wled_bedroom
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled_bedroom
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled_bedroom
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled_bedroom
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled_bedroom
            - delay: 00:02:00
            - service: light.turn_off
              entity_id: light.wled_bedroom
    - condition: or
      conditions:
          - condition: state
            entity_id: light.wled_bedroom
            state: "on"
          - condition: state
            entity_id: light.wled_bedroom
            state: unavailable
          - condition: state
            entity_id: light.wled_bedroom
            state: unknown
    - service: telegram_bot.send_message
      data:
        message: |
            ⚠️ Лента в спальне не выключилась в течение 10 минут.
    - delay: 00:00:05

- alias: "033_light_bedroom_3%_strip_on_22:00"
  description: 'Измение яркости после 22:00'
  trigger:
    - platform: time_pattern
      minutes: '/10'
  condition: 
    - condition: state
      entity_id: input_boolean.auto_light_bedroom_on_off
      state: 'on'
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
    - condition: time
      after: '22:00:00'
    - condition: state
      entity_id: light.wled_bedroom
      state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.wled_bedroom
        brightness_pct: 5

- alias: "033_light_bedroom_50%_on"
  description: 'Включение подсветки по времени с уведомлением о задержке и повторным включением'
  trigger:
    - platform: time
      at: input_datetime.light_bedroom_on
  condition:
    - condition: state
      entity_id: input_boolean.auto_light_bedroom_on_off
      state: 'on'
    - condition: state
      entity_id: input_boolean.control_mode
      state: 'on'
    - condition: and
      conditions:
        - condition: state
          entity_id:
            - light.wled_bedroom
          match: any
          state: "off"
  action:
    - repeat:
        while:
          - condition: or
            conditions:
              - condition: state
                entity_id: light.wled_bedroom
                state: "off"
              - condition: state
                entity_id: light.wled_bedroom
                state: unavailable
              - condition: state
                entity_id: light.wled_bedroom
                state: unknown
        sequence:
            - service: light.turn_on
              data:
                entity_id: light.wled_bedroom
                brightness_pct: 25
            - service: select.select_option
              data:
                option: Preset 3
              target:
                entity_id: select.wled_bedroom_preset
            - delay: 00:02:00
            - service: light.turn_on
              data:
                entity_id: light.wled_bedroom
                brightness_pct: 25
            - service: select.select_option
              data:
                option: Preset 3
              target:
                entity_id: select.wled_bedroom_preset
            - delay: 00:02:00
            - service: light.turn_on
              data:
                entity_id: light.wled_bedroom
                brightness_pct: 25
            - service: select.select_option
              data:
                option: Preset 3
              target:
                entity_id: select.wled_bedroom_preset
            - delay: 00:02:00
            - service: light.turn_on
              data:
                entity_id: light.wled_bedroom
                brightness_pct: 25
            - service: select.select_option
              data:
                option: Preset 3
              target:
                entity_id: select.wled_bedroom_preset
            - delay: 00:02:00
            - service: light.turn_on
              data:
                entity_id: light.wled_bedroom
                brightness_pct: 25
            - service: select.select_option
              data:
                option: Preset 3
              target:
                entity_id: select.wled_bedroom_preset
            - delay: 00:02:00
            - service: light.turn_on
              data:
                entity_id: light.wled_bedroom
                brightness_pct: 25
            - service: select.select_option
              data:
                option: Preset 3
              target:
                entity_id: select.wled_bedroom_preset
    - condition: or
      conditions:
          - condition: state
            entity_id: light.wled_bedroom
            state: "off"
          - condition: state
            entity_id: light.wled_bedroom
            state: unavailable
          - condition: state
            entity_id: light.wled_bedroom
            state: unknown
    - service: telegram_bot.send_message
      data:
        message: |
            ⚠️ Лента в спальне не включилась в течение 10 минут.
    - delay: 00:00:05

- alias: "033_light_bedroom_turn_on_automatic_preset_3"
  description: 'Применение пресета после сброса питания'
  trigger:
  - platform: state
    entity_id:
    - light.wled_bedroom
    from: 'off'
    to: 'on'
  condition: 
  - condition: state
    entity_id: input_boolean.auto_light_bedroom_on_off
    state: 'on'
  - condition: state
    entity_id: input_boolean.control_mode
    state: 'on'
  action:
  - service: select.select_option
    data:
      option: Preset 3
    target:
      entity_id: select.wled_bedroom_preset
  - service: light.turn_on
    data:
      entity_id: light.wled_bedroom
      brightness_pct: 25
  mode: single
  