title: Home Assistant
views:
    - !include lovelace/lo_home.yaml
    - !include lovelace/lo_devices.yaml
    - !include lovelace/lo_system.yaml
    - !include lovelace/lo_electricity.yaml
    - !include lovelace/lo_cctv.yaml