custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
title: Home Assistant
background: var(--background-image)
views:
    - !include lovelace/lo_home.yaml
    - !include lovelace/lo_devices.yaml
    - !include lovelace/lo_system.yaml
    - !include lovelace/lo_electricity.yaml
    - !include lovelace/lo_cctv.yaml