- platform: systemmonitor
  resources:
  - type: processor_temperature
  - type: processor_use
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: last_boot
  - type: disk_free
    arg: /

# - platform: command_line
#   name: CPU Temp
#   command: "cat /sys/class/thermal/thermal_zone2/temp"
#   unit_of_measurement: "°C"
#   value_template: '{{ (value | multiply(0.001)) | round(1) }}'
  
- platform: time_date
  display_options:
      - 'time'
      - 'date'
      - 'beat'
      - 'date_time'

# - platform: systemmonitor
#   resources:
#   - type: disk_use_percent
#     arg: /config
#   - type: disk_use
#   - type: disk_free
#   - type: memory_use_percent
#   - type: memory_use
#   - type: memory_free
#   - type: swap_use_percent
#   - type: swap_use
#   - type: swap_free
#   - type: load_1m
#   - type: load_5m
#   - type: load_15m
#   - type: network_in
#     arg: eth0
#   - type: network_out
#     arg: eth0
#   - type: throughput_network_in
#     arg: eth0
#   - type: throughput_network_out
#     arg: eth0
#   - type: packets_in
#     arg: eth0
#   - type: packets_out
#     arg: eth0
#   - type: ipv4_address
#     arg: eth0
#   - type: ipv6_address
#     arg: eth0
#   - type: processor_use
#   - type: processor_temperature
#   - type: last_boot

# - platform: command_line
#   name: supervisor_updates
#   command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version,"update_available":.data.update_available,"addons":[.data.addons[] | select(.update_available)]}'''
#   value_template: "{{ value_json.addons | length }}"
#   unit_of_measurement: доступно обновлений
#   json_attributes:
#   - update_available
#   - newest_version
#   - current_version
#   - addons


